### ISSUE TITLE
S3UploadFailedError

### ISSUE THREAD

**Issue by rosall** [aws-samples/aws-panorama-samples#24]
When running the cell in the people counter example notebook:
```
s3.meta.client.upload_file('{}/panorama_sdk/models/{}.tar.gz'.format(workdir,ML_MODEL_FNAME), 
                           S3_BUCKET, '{}/{}.tar.gz'.format(project_name, ML_MODEL_FNAME))
```
I get this error:
```
S3UploadFailedError: Failed to upload /home/ubuntu/awspanoramasamples/samples/panorama_sdk/models/ssd_512_resnet50_v1_voc.tar.gz to panorama-xyz/people_counter/ssd_512_resnet50_v1_voc.tar.gz: An error occurred (AccessDenied) when calling the CreateMultipartUpload operation: Access Denied
```

I have tried changing the S3 bucket policy to allow access, but that didn't solve it. My setup is the same as in the tutorial. Any help would be appreciated.

**Comment by shimomut** [comment]
@rosall , thank you for your report.

Could you please check if your IAM Role or IAM User you are using to run the notebook, has permission to put objects in the S3 bucket you provided to "S3_BUCKET" variable?

**Comment by shimomut** [comment]
@rosall , I am closing this item, but please let us know when you still see this issue.
