### ISSUE TITLE
how to pump streams into kvs?

### ISSUE THREAD

**Issue by mattfeury** [aws-samples/aws-panorama-samples#27]
hello,

playing with these boxes and they look appealing. i'm noticing that the current architecture is more for processing things on a frame by frame basis. i'm interested in pumping data into KVS, but KVS only accepts h264/encoded stream data. This is normally very easy when i have an RTSP url because I can use the KVS gstreamer sink to just pipe them together. However, since i don't have access to the underlying URL (i can get stream_url but no credentials), i have to work with single image frames.

the [docs say](https://aws.amazon.com/panorama/faqs/):
> AWS Panorama application results can be integrated with on-premises line of business applications for automation and can be routed to services such as Amazon Simple Storage Service (S3), **Amazon Kinesis Video Streams**, or Amazon CloudWatch for deriving actionable insights to drive process improvements.

is there a preferred approach to get data to pump into KVS?

thanks!

**Comment by jk1333** [comment]
I definitely need this feature, there should way to encode video with overlayed info(rect, label and so on) to KVS by platform layer without performance issues.

**Comment by shimomut** [comment]
@mattfeury, @jk1333,

Currently, Panorama doesn't have out of box integration with KVS, but customers can use the Kinesis Producer Library to do this.
Kinesis Producer Library expects the stream to be in MKV format so customers will have to create MKV data on the Panorama appliance device.

**Comment by shimomut** [comment]
Closing this item.

**Comment by mrtj** [comment]
Hello @mattfeury and @jk1333, I've just published my library and an article explaining it on how to stream the video output of your Panorama app to KVS or to a local RTSP server. 
 - article: https://towardsdatascience.com/remote-view-your-computer-vision-models-running-on-aws-panorama-32922369ecf
 - library: https://github.com/Neosperience/backpack
