### ISSUE TITLE
Commands in run_after_clone.sh script in panorama_sdk are incorrect

### ISSUE THREAD

**Issue by ranrotx** [aws-samples/aws-panorama-samples#3]
In the README.md file, there are instructions to run ```sh-4.2$ sudo sh aws-panorama-samples/panorama_sdk/run_after_clone.sh``` but this produces the following:
```
chown: cannot access ‘AWSOmniCVExamples/’: No such file or directory
chgrp: cannot access ‘AWSOmniCVExamples/’: No such file or directory
```

It appears that the folder structure has changed. Recommend either removing this step or telling users to manually run the appropriate ```chown``` and ```chgrp``` commands.

**Comment by SuryaKari** [comment]
Thank you for flagging this. 

The link **https://panorama-starter-kit.s3.amazonaws.com/public/v1/Models/panorama_sdk.zip** has been updated with the right run_after_clone.sh file. Please re-pull the panorama_sdk and it should work.

**Comment by ranrotx** [comment]
Appears to have been resolved. Thanks!
