### ISSUE TITLE
Camera node has to be after Code node when running with Test-Utility 

### ISSUE THREAD

**Issue by shimomut** [aws-samples/aws-panorama-samples#31]
In order to run the app with Test-Utility, Camera node has to be defined after code node, otherwise, node.video_in.get() API fails with Assertion failure.

**Comment by mrtj** [comment]
I also hit this bug. The apparent reason is that `panoramasdk.getgraphdata.getlistofnodes()` method writes two times two different object for the key `video_in` (contained in the `node_name_edge` variable) in the returned dictionary. 

https://github.com/aws-samples/aws-panorama-samples/blob/4541c56f3c25289499674d748693e9b71888d094/samples/common/test_utility/panoramasdk.py#L233-L242

If the nodes are connected in the "standard" way, i.e.:
```json
{
    "edges": [
        {
            "producer": "camera_input.video_out",
            "consumer": "code_node.video_in"
        },
        {
            "producer": "code_node.video_out",
            "consumer": "display_output.video_in"
        }
    ]
}
```

in `graph.json`, then `node_name_edge` will take two times the value `video_in`, once for the code node, next time for the camera node. They are enumerated in the order of the node list in graph.json, so if the code node comes after the camera node, it will fill the video_in input incorrectly with the code node value.

I tried to decipher what this edge dict (and other "data structures" in the code) are supposed to contain, but it honestly the quality of this code is so low that I could not figure it out. 

If the owners decide to rewrite the emulator from scratch at once, I would be happy to partecipate.

**Comment by shimomut** [comment]
@mrtj
Thank you for your comment. I worked on the fix from last week, and created a pull-request. As you wrote, it was difficult to understand the original code and was easier to rewrite.

This is pending Pull-request I created, and will merge soon : https://github.com/aws-samples/aws-panorama-samples/pull/33

**Comment by shimomut** [comment]
The pull request was merged, and I confirmed that it fixes this issue. Closing.
