### ISSUE TITLE
media.stream_id missing

### ISSUE THREAD

**Issue by jk1333** [aws-samples/aws-panorama-samples#44]
Hello!
It seems there are some new attributes added to platform as shown below
https://github.com/awsdocs/aws-panorama-developer-guide/blob/main/resources/applicationsdk-reference.md

But when I tested on appliance or through sdk, I can't find stream_id and is_cached attributes.
When will be added to platform ?

**Comment by shimomut** [comment]
@jk1333 ,

Thank you for reporting this issue. The new properties are added to real hardware version of panoramasdk, but they have not been added to the Test Utility (simulation environment) version of panoramasdk yet, and we will add them. Thank you for pointing out. We will keep this item open, and update once they are added.

**Comment by jk1333** [comment]
The fix has merged through mot sample so we can close
