### ISSUE TITLE
 SNeoModel(104) Cannot find Neo dlr in model directory using default Neo dlr

### ISSUE THREAD

**Issue by G-Slient** [aws-samples/aws-panorama-samples#6]
I have deployed the **People Counter Example.**
I got the below error in CloudWatch logs 

![image](https://user-images.githubusercontent.com/37027189/107240291-c2e9e080-6a4f-11eb-9770-bc55f623d5d1.png)

How to fix this issue ?

**Comment by strawberrypie** [comment]
I've encountered the same problem. You should check if you have the same model name in `model.open` in lambda function and in Panorama model repository.
