### ISSUE TITLE
Deployment error - GPU containers - PT37 sample

### ISSUE THREAD

**Issue by vinodjsr** [aws-samples/aws-panorama-samples#79]
Hi,

I am trying to deploy the PT37 model (uses GPU) on aws panorama which already has people_counter_app and pose_estimation deployed.
The deployment error given is --
" Containers requesting GPU privileges cannot coexist with existing applications on the device that have model nodes. Failed validation for account:{accound_id}, device:arn:aws:panorama:us-east-1:{accound_id}:device/device-*"

Cant we deploy models that use/dont use GPU on the same machine at the same time?

Is it that we can either deploy models  that dont use GPU or that use GPU on the same machine?

Please guide as there is no documentation on this. I was under impression that we can deploy multiple models (some might be using GPU) on the same machine concurrently!

Thanks.

**Comment by shimomut** [comment]
Hi @vinodjsr ,

That restriction is due to security reason, and it is briefly explained in this doc (In the Red box):
https://docs.aws.amazon.com/panorama/latest/dev/applications-gpuaccess.html

By deleting the people_counter_app (which uses Model node), you can deploy PT37 app (which uses direct-GPU).
Closing this item, but please let us know if you need more information.

**Comment by pavelbugneac** [comment]
Hey @vinodjsr, from my experience working with panorama, this means that you cannot have a “direct-gpu” app running with a regular app (which uses model nodes) at the same time. Technically you don’t have to make use of the GPU to run inference with “direct-gpu” apps. These type of apps give you access to the gpu but you do whatever you want with it. You could deploy two of them but then in one of them simply use cpu for inference. However, this way you can’t make use of the model node, but you could use PyTorch (or other frameworks) directly and maybe specify that it uses cpu. Hope this helps.

**Comment by vinodjsr** [comment]
Thanks @shimomut and @pavelbugneac for the resolution and help. 👍
