### ISSUE TITLE
car_tracker_tutorial.ipynb failed with S3 404 error due to the wrong path `--model-s3-uri` of `panorama-cli add-raw-model`

### ISSUE THREAD

**Issue by hightensan** [aws-samples/aws-panorama-samples#87]
In the [car_tracker_tutorial.ipynb](https://github.com/aws-samples/aws-panorama-samples/blob/main/samples/car_tracker/car_tracker_tutorial.ipynb) sample notebook, the below cell is failed with S3 404 error.

```
!cd ./car_tracker_app && panorama-cli add-raw-model \
    --model-asset-name {model_asset_name} \
    --model-s3-uri s3://{S3_BUCKET}/{app_name}/{ML_MODEL_FNAME}.tar.gz \
    --descriptor-path {model_descriptor_path}  \
    --packages-path {model_package_path}
```

The cause is `--model-s3-uri` is the wrong path, which does not contain `{model_node_name}`.
- Fail : --model-s3-uri s3://{S3_BUCKET}/{app_name}/{ML_MODEL_FNAME}.tar.gz
- Success : --model-s3-uri s3://{S3_BUCKET}/{app_name}/{model_node_name}/{ML_MODEL_FNAME}.tar.gz

SageMaker Com pilation job's output is specified as `s3://{S3_BUCKET}/{app_name}/{model_node_name}/`, so the path should contain `/{model_node_name}/` prefix.

```
$ aws sagemaker describe-compilation-job --compilation-job-name Comp-Job20230714012911AM --region us-east-1 | jq '.OutputConfig'
{
  "S3OutputLocation": "s3://test-aws-panorama-samples-bucket-us-east-1/car_tracker_app/model_node/",
  "TargetPlatform": {
    "Os": "LINUX",
    "Arch": "X86_64"
  }
}
```

![Screenshot 2023-07-14 at 11 02 18](https://github.com/aws-samples/aws-panorama-samples/assets/48213915/1a4b2458-85e2-4447-92d5-1944dd272376)

**Comment by shimomut** [comment]
Merged the PR. Thank you!
